#!/bin/bash

# Illuminateur 手动部署指南
# 由于 wrangler login 问题，改为手动操作指引

echo "🔍 Illuminateur 手动部署指南"
echo "=============================="
echo ""
echo "由于 wrangler CLI 登录问题，请按以下步骤手动操作："
echo ""
echo "📋 步骤 1: 在 Cloudflare Dashboard 中创建资源"
echo "-------------------------------------------"
echo "1. 访问 https://dash.cloudflare.com"
echo "2. 登录你的 Cloudflare 账户"
echo ""
echo "🗄️ 创建 D1 数据库:"
echo "1. 进入 'Workers & Pages' > 'D1 SQL Database'"
echo "2. 点击 'Create database'"
echo "3. 数据库名称: illuminateur-db"
echo "4. 创建完成后，复制 Database ID"
echo ""
echo "📦 创建 R2 存储桶:"
echo "1. 进入 'R2 Object Storage'"
echo "2. 点击 'Create bucket'"
echo "3. 存储桶名称: illuminateur-storage"
echo "4. 选择合适的区域"
echo ""
echo "📋 步骤 2: 更新配置文件"
echo "------------------------"
echo "1. 编辑 wrangler.toml 文件"
echo "2. 将 database_id 替换为步骤1中复制的 Database ID"
echo "3. 确保 bucket_name 为 illuminateur-storage"
echo ""
echo "📋 步骤 3: 初始化数据库"
echo "------------------------"
echo "1. 在 Cloudflare Dashboard 的 D1 数据库页面"
echo "2. 点击 'Console' 标签"
echo "3. 复制 schema.sql 文件的内容并执行"
echo "4. 或者使用命令: wrangler d1 execute illuminateur-db --file=./schema.sql"
echo ""
echo "📋 步骤 4: 创建 Worker"
echo "-------------------"
echo "1. 进入 'Workers & Pages' > 'Overview'"
echo "2. 点击 'Create application' > 'Create Worker'"
echo "3. Worker 名称: illuminateur"
echo "4. 点击 'Deploy' 创建基础 Worker"
echo ""
echo "📋 步骤 5: 配置 Worker"
echo "-------------------"
echo "1. 在 Worker 详情页面，点击 'Settings' > 'Variables'"
echo "2. 添加环境变量:"
echo "   - ACCESS_TOKEN: 你的访问令牌（自定义）"
echo "   - GEMINI_API_KEY: 你的 Gemini API 密钥"
echo "3. 在 'Settings' > 'Bindings' 中添加:"
echo "   - D1 Database: 变量名 D1_DB，选择 illuminateur-db"
echo "   - R2 Bucket: 变量名 R2_BUCKET，选择 illuminateur-storage"
echo ""
echo "📋 步骤 6: 部署代码"
echo "------------------"
echo "1. 复制 src/index.js 的全部内容"
echo "2. 在 Worker 详情页面，点击 'Quick edit'"
echo "3. 粘贴代码并点击 'Save and deploy'"
echo ""
echo "📋 步骤 7: 测试应用"
echo "------------------"
echo "1. 访问 Worker 的 URL"
echo "2. 输入你设置的 ACCESS_TOKEN"
echo "3. 测试文本、URL、图片分析功能"
echo ""
echo "🔧 获取 Gemini API 密钥:"
echo "1. 访问 https://makersuite.google.com/app/apikey"
echo "2. 登录 Google 账户并创建 API 密钥"
echo ""
echo "❓ 如果遇到问题:"
echo "1. 检查所有绑定是否正确配置"
echo "2. 确认环境变量已正确设置"
echo "3. 查看 Worker 的实时日志排查错误"
echo ""
echo "✅ 完成后，你的 Illuminateur 应用就可以使用了！"