name = "inspiration-collector"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages配置
[env.production]
name = "inspiration-collector"

# D1 数据库绑定 (暂时注释掉，需要创建后填入实际ID)
# [[d1_databases]]
# binding = "DB"
# database_name = "inspiration-db"
# database_id = "your_database_id_here"

# KV 存储绑定 (暂时注释掉，需要创建后填入实际ID)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your_kv_namespace_id_here"
# preview_id = "your_kv_preview_id_here"

# 环境变量
[vars]
GEMINI_API_KEY = "" # 需要在Cloudflare Dashboard中设置
ENVIRONMENT = "development"

# Workers配置
[build]
command = "npm run build"

# 本地开发配置
[dev]
port = 3000
local_protocol = "http"
local = true