name = "illuminateur"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
ENVIRONMENT = "production"

# D1 数据库绑定
[[d1_databases]]
binding = "D1_DB"
database_name = "illuminateur-db"
database_id = "your-database-id-here"  # 需要替换为实际的数据库 ID

# R2 存储绑定
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "illuminateur-storage"

# AI 绑定 (Cloudflare AI)
[ai]
binding = "AI"

# 定时任务 - 每周日生成洞察报告
[[triggers.crons]]
cron = "0 9 * * 0"  # 每周日上午9点

# Pages 构建配置
[build]
command = "npm run build"
watch_dir = "src"