name = "illuminateur"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Secrets (set via wrangler secret put)
# ACCESS_TOKEN - Authentication token for the application
# GEMINI_API_KEY - Google Gemini API key

# R2 Object Storage binding
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "illuminateur-storage"

# D1 Database binding
[[d1_databases]]
binding = "D1_DB"
database_name = "illuminateur-db"
database_id = "your-database-id-here"

# AI binding for Cloudflare AI
[ai]
binding = "AI"

# Cron trigger for weekly insights
[triggers]
crons = ["0 0 * * 0"]  # Every Sunday at midnight UTC

# Build configuration
[build]
command = "npm run build"

# Development configuration
[env.development]
[env.development.vars]
ENVIRONMENT = "development"