name = "illuminateur"
main = "src/index.js"
compatibility_date = "2024-01-01"

# 环境变量配置
[vars]
ENVIRONMENT = "development"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "illuminateur-db"
database_id = "your-database-id-here"

# 生产环境配置
[env.production]
name = "illuminateur-prod"

[env.production.vars]
ENVIRONMENT = "production"

# 需要在Cloudflare Dashboard中设置的环境变量:
# ACCESS_TOKEN - 用于登录验证的访问令牌
# GEMINI_API_KEY - Gemini API密钥
# GEMINI_BASE_URL - Gemini API基础URL (默认: https://generativelanguage.googleapis.com)
# MODEL_NAME - 使用的模型名称 (默认: gemini-pro)